# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'program.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1154)
        MainWindow.setStyleSheet("background-color: rgb(70, 117, 56);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Developer = QtWidgets.QTabWidget(self.centralwidget)
        self.Developer.setGeometry(QtCore.QRect(40, 50, 1900, 1000))
        self.Developer.setStyleSheet("font: 16pt \"Calibri\";")
        self.Developer.setObjectName("Developer")
        self.Standard = QtWidgets.QWidget()
        self.Standard.setObjectName("Standard")
        self.lbl = QtWidgets.QLabel(self.Standard)
        self.lbl.setGeometry(QtCore.QRect(20, 30, 451, 41))
        self.lbl.setStyleSheet("font: 24pt \"Calibri\";")
        self.lbl.setObjectName("lbl")
        self.run_main_btn = QtWidgets.QPushButton(self.Standard)
        self.run_main_btn.setGeometry(QtCore.QRect(110, 130, 251, 71))
        self.run_main_btn.setStyleSheet("background-color: rgb(175, 255, 80);")
        self.run_main_btn.setObjectName("run_main_btn")
        self.Developer.addTab(self.Standard, "")
        self.Developer1 = QtWidgets.QWidget()
        self.Developer1.setObjectName("Developer1")
        self.canny_thres_slider = QtWidgets.QSlider(self.Developer1)
        self.canny_thres_slider.setGeometry(QtCore.QRect(680, 330, 211, 21))
        self.canny_thres_slider.setMaximum(1024)
        self.canny_thres_slider.setProperty("value", 500)
        self.canny_thres_slider.setSliderPosition(500)
        self.canny_thres_slider.setOrientation(QtCore.Qt.Horizontal)
        self.canny_thres_slider.setObjectName("canny_thres_slider")
        self.canny_thres_label = QtWidgets.QLabel(self.Developer1)
        self.canny_thres_label.setGeometry(QtCore.QRect(680, 250, 321, 31))
        self.canny_thres_label.setStyleSheet("font: 16pt \"Calibri\";")
        self.canny_thres_label.setObjectName("canny_thres_label")
        self.label_Camera = QtWidgets.QLabel(self.Developer1)
        self.label_Camera.setGeometry(QtCore.QRect(30, 20, 480, 360))
        self.label_Camera.setObjectName("label_Camera")
        self.run_camera_feed_btn = QtWidgets.QPushButton(self.Developer1)
        self.run_camera_feed_btn.setGeometry(QtCore.QRect(660, 80, 301, 41))
        self.run_camera_feed_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.run_camera_feed_btn.setStyleSheet("background-color: rgb(175, 255, 80);")
        self.run_camera_feed_btn.setCheckable(False)
        self.run_camera_feed_btn.setObjectName("run_camera_feed_btn")
        self.label_Canny = QtWidgets.QLabel(self.Developer1)
        self.label_Canny.setGeometry(QtCore.QRect(30, 580, 480, 360))
        self.label_Canny.setObjectName("label_Canny")
        self.Developer.addTab(self.Developer1, "")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1941, 1081))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../../../../../../Users/ppvr3/Downloads/output-onlinepngtools.png"))
        self.label.setObjectName("label")
        self.label.raise_()
        self.Developer.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionStandardMode = QtWidgets.QAction(MainWindow)
        self.actionStandardMode.setObjectName("actionStandardMode")

        self.retranslateUi(MainWindow)
        self.Developer.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Pooltable Next Level"))
        self.lbl.setText(_translate("MainWindow", "Pooltable Next Level"))
        self.run_main_btn.setText(_translate("MainWindow", "Run Main Program"))
        self.Developer.setTabText(self.Developer.indexOf(self.Standard), _translate("MainWindow", "Standard"))
        self.canny_thres_label.setText(_translate("MainWindow", "canny_thres_label"))
        self.label_Camera.setText(_translate("MainWindow", "Labelcamera"))
        self.run_camera_feed_btn.setText(_translate("MainWindow", "RunCameraFeed"))
        self.label_Canny.setText(_translate("MainWindow", "LabelCanny"))
        self.Developer.setTabText(self.Developer.indexOf(self.Developer1), _translate("MainWindow", "Developer"))
        self.actionStandardMode.setText(_translate("MainWindow", "StandardMode"))
