# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        MainWindow.setStyleSheet("background-color: rgb(167, 255, 192);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Developer = QtWidgets.QTabWidget(self.centralwidget)
        self.Developer.setGeometry(QtCore.QRect(30, 30, 1200, 660))
        self.Developer.setStyleSheet("font: 16pt \"Calibri\";")
        self.Developer.setObjectName("Developer")
        self.Standard = QtWidgets.QWidget()
        self.Standard.setObjectName("Standard")
        self.lbl = QtWidgets.QLabel(self.Standard)
        self.lbl.setGeometry(QtCore.QRect(20, 30, 451, 41))
        self.lbl.setStyleSheet("color: rgb(0, 170, 28);\n"
"font: 24pt \"Calibri\";")
        self.lbl.setObjectName("lbl")
        self.btn = QtWidgets.QPushButton(self.Standard)
        self.btn.setGeometry(QtCore.QRect(70, 140, 351, 181))
        self.btn.setStyleSheet("background-color: rgb(94, 145, 255);\n"
"font: 28pt \"MS Shell Dlg 2\";")
        self.btn.setObjectName("btn")
        self.Developer.addTab(self.Standard, "")
        self.Developer1 = QtWidgets.QWidget()
        self.Developer1.setObjectName("Developer1")
        self.Slider = QtWidgets.QSlider(self.Developer1)
        self.Slider.setGeometry(QtCore.QRect(90, 110, 211, 21))
        self.Slider.setOrientation(QtCore.Qt.Horizontal)
        self.Slider.setObjectName("Slider")
        self.label = QtWidgets.QLabel(self.Developer1)
        self.label.setGeometry(QtCore.QRect(130, 50, 151, 31))
        self.label.setStyleSheet("font: 16pt \"Calibri\";")
        self.label.setObjectName("label")
        self.label_Camera = QtWidgets.QLabel(self.Developer1)
        self.label_Camera.setGeometry(QtCore.QRect(80, 200, 480, 360))
        self.label_Camera.setObjectName("label_Camera")
        self.Developer.addTab(self.Developer1, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionStandardMode = QtWidgets.QAction(MainWindow)
        self.actionStandardMode.setObjectName("actionStandardMode")

        self.retranslateUi(MainWindow)
        self.Developer.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Pooltable Next Level"))
        self.lbl.setText(_translate("MainWindow", "Pooltable Next Level"))
        self.btn.setText(_translate("MainWindow", "RUN"))
        self.Developer.setTabText(self.Developer.indexOf(self.Standard), _translate("MainWindow", "Standard"))
        self.label.setText(_translate("MainWindow", "SliderValue"))
        self.label_Camera.setText(_translate("MainWindow", "Labelcamera"))
        self.Developer.setTabText(self.Developer.indexOf(self.Developer1), _translate("MainWindow", "Developer"))
        self.actionStandardMode.setText(_translate("MainWindow", "StandardMode"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
