# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'program.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1154)
        MainWindow.setStyleSheet("background-color: rgb(70, 117, 56);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Developer = QtWidgets.QTabWidget(self.centralwidget)
        self.Developer.setGeometry(QtCore.QRect(0, 0, 1900, 1000))
        self.Developer.setAutoFillBackground(False)
        self.Developer.setStyleSheet("font: 14pt \"Calibri\";")
        self.Developer.setObjectName("Developer")
        self.Standard = QtWidgets.QWidget()
        self.Standard.setObjectName("Standard")
        self.lbl = QtWidgets.QLabel(self.Standard)
        self.lbl.setGeometry(QtCore.QRect(270, 160, 681, 171))
        self.lbl.setStyleSheet("font: 48pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(5, 90, 0);")
        self.lbl.setObjectName("lbl")
        self.run_main_btn = QtWidgets.QPushButton(self.Standard)
        self.run_main_btn.setGeometry(QtCore.QRect(720, 430, 491, 201))
        self.run_main_btn.setStyleSheet("background-color: rgb(175, 255, 80);\n"
"font: 28pt \"MS Shell Dlg 2\";")
        self.run_main_btn.setObjectName("run_main_btn")
        self.label = QtWidgets.QLabel(self.Standard)
        self.label.setGeometry(QtCore.QRect(10, 10, 1851, 941))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Dependencies\pooltable_background.jpg"))
        self.label.setObjectName("label")
        self.label.raise_()
        self.lbl.raise_()
        self.run_main_btn.raise_()
        self.Developer.addTab(self.Standard, "")
        self.Developer1 = QtWidgets.QWidget()
        self.Developer1.setObjectName("Developer1")
        self.canny_thres_slider = QtWidgets.QSlider(self.Developer1)
        self.canny_thres_slider.setGeometry(QtCore.QRect(830, 340, 211, 21))
        self.canny_thres_slider.setStyleSheet("background-color: rgb(5, 90, 0);")
        self.canny_thres_slider.setMaximum(1024)
        self.canny_thres_slider.setProperty("value", 500)
        self.canny_thres_slider.setSliderPosition(500)
        self.canny_thres_slider.setOrientation(QtCore.Qt.Horizontal)
        self.canny_thres_slider.setObjectName("canny_thres_slider")
        self.canny_thres_label = QtWidgets.QLabel(self.Developer1)
        self.canny_thres_label.setGeometry(QtCore.QRect(830, 280, 321, 31))
        self.canny_thres_label.setStyleSheet("font: 16pt \"Calibri\";\n"
"background-color: rgb(5, 90, 0);")
        self.canny_thres_label.setObjectName("canny_thres_label")
        self.label_Camera = QtWidgets.QLabel(self.Developer1)
        self.label_Camera.setGeometry(QtCore.QRect(220, 120, 480, 360))
        self.label_Camera.setStyleSheet("background-color: rgb(5, 90, 0);")
        self.label_Camera.setObjectName("label_Camera")
        self.run_camera_feed_btn = QtWidgets.QPushButton(self.Developer1)
        self.run_camera_feed_btn.setGeometry(QtCore.QRect(830, 200, 301, 41))
        self.run_camera_feed_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.run_camera_feed_btn.setStyleSheet("background-color: rgb(175, 255, 80);")
        self.run_camera_feed_btn.setCheckable(False)
        self.run_camera_feed_btn.setObjectName("run_camera_feed_btn")
        self.label_Canny = QtWidgets.QLabel(self.Developer1)
        self.label_Canny.setGeometry(QtCore.QRect(220, 480, 480, 360))
        self.label_Canny.setStyleSheet("background-color: rgb(5, 90, 0);")
        self.label_Canny.setObjectName("label_Canny")
        self.label_2 = QtWidgets.QLabel(self.Developer1)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 1851, 941))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("Dependencies\pooltable_background.jpg"))
        self.label_2.setObjectName("label_2")
        self.label_2.raise_()
        self.canny_thres_slider.raise_()
        self.canny_thres_label.raise_()
        self.label_Camera.raise_()
        self.run_camera_feed_btn.raise_()
        self.label_Canny.raise_()
        self.Developer.addTab(self.Developer1, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionStandardMode = QtWidgets.QAction(MainWindow)
        self.actionStandardMode.setObjectName("actionStandardMode")

        self.retranslateUi(MainWindow)
        self.Developer.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Pooltable Next Level"))
        self.lbl.setText(_translate("MainWindow", "Pooltable Next Level"))
        self.run_main_btn.setText(_translate("MainWindow", "Run Main Program"))
        self.Developer.setTabText(self.Developer.indexOf(self.Standard), _translate("MainWindow", "Standard"))
        self.canny_thres_label.setText(_translate("MainWindow", "canny_thres_label"))
        self.label_Camera.setText(_translate("MainWindow", "Labelcamera"))
        self.run_camera_feed_btn.setText(_translate("MainWindow", "RunCameraFeed"))
        self.label_Canny.setText(_translate("MainWindow", "LabelCanny"))
        self.Developer.setTabText(self.Developer.indexOf(self.Developer1), _translate("MainWindow", "Developer"))
        self.actionStandardMode.setText(_translate("MainWindow", "StandardMode"))
